### ISSUE TITLE
Bring readxl into the tidyverse

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#241]
### Initial transfer

  * [x] Move to tidyverse organisation.
  * [x] Search for `hadley/` and replace with `tidyverse/`.
  * [x] Modify `.git/config`

### travis

  * [x] Make sure includes:

```yaml
r:
 - oldrel
 - release
 - devel
```

### pkgdown

  * [x] Add template `_pkgdown.yml`

```yaml
template:
  package: tidytemplate
  default_assets: false
```

  * [x] Add to `.Rbuildignore`

  * [x] `build_site()` then push.

  * [x] In admin use `docs/` for documentation and turn off wiki

  * [x] create `docs/CNAME` consisting of `PACKAGE.tidyverse.org`

  * [x] Update url on github repo page.

  * [x] Add url to DESCRIPTION.

  * [x] Group functions deliberately in function reference.

### Logo

  * [x] Copy in hex logo (120 x 139) ~~and add to `.Rbuildignore`~~.

  * [x] Package name + hex logo.

```
# {{package name}} <img src="logo.png" align="right" />
```

  * [x] Add image + link on <http://tidyverse.org>

### `README.Rmd`

  * [x] Switch from `.md` to `.Rmd`

  * [x] Install instructions:

````r
```{r, eval = FALSE}
# The easiest way to get readr is to install the whole tidyverse:
install.packages("tidyverse")

# Alternatively, install just readr:
 install.packages("readr")

# Or the the development version from GitHub:
# install.packages("devtools")
devtools::install_github("tidyverse/readr")
```
````

  * [x] Overview: 1-2 paragraphs including brief description/goals. Add h2, and set:

   ```yaml
   home:
     strip_header: true
   ```

  * [x]  Link to appropriate R4DS chapter:

   ```md
   If you are new to readr, the best place to start is the
   [data import chapter](http://r4ds.had.co.nz/data-import.html) in R
   for data science.
   ```

  * [x] Add link to `_pkgdown.yaml`

   ```yaml
     links:
     - text: Learn more
       href: http://r4ds.had.co.nz/data-import.html
   ```

  * [x]  Usage section shows a few examples.

### Package help

  * [x] Review package title and description in DESCRIPTION.

  * [x] Ensure that RStudio is listed as funder.

  * [x] Add package help page.

   ```r
   #' @keywords internal
   "_PACKAGE"
   ```

  * [x] Switch to markdown, while there is still so little documentation *JB addition*

  * [x] Review topic titles. Check for trailing full stops.

### Articles

  * [x] Ensure all vignettes neither date, nor author.

  * [x] Write `vignette/packagename.Rmd` which expands on README.

  * [x] Add direct links to navbar.

   ```yaml
   - text: Intro
     href: articles/stringr.html
   - text: RegEx
     href: articles/regular-expressions.html
   ```

  * [x] Translate blog posts to `vignettes/releases`. Update navbar.

   ```yaml
   - text: News
     menu:
     - text: "Release notes"
     - text: "Version 1.1.0"
       href: articles/releases/stringr-1.1.0.html
     - text: "Version 1.0.0"
       href: articles/releases/stringr-1.0.0.html
     - text: "------------------"
     - text: "Change log"
       href: news/index.html
   ```
